name: Build firmware

on:
  workflow_dispatch:
    inputs:
      model:
        description: 'Model to build'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - rm-ac2100
          - mi-3
          - mi-r3gv2
  push:
    tags:
      - 'v*'
  schedule:
    - cron: '30 6 * * 1'

jobs:
  rm-ac2100:
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.model == 'all' || github.event.inputs.model == 'rm-ac2100' }}
    uses: ./.github/workflows/build-one.yml
    with:
      model: rm-ac2100

  mi-3:
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.model == 'all' || github.event.inputs.model == 'mi-3' }}
    uses: ./.github/workflows/build-one.yml
    with:
      model: mi-3

  mi-r3gv2:
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.model == 'all' || github.event.inputs.model == 'mi-r3gv2' }}
    uses: ./.github/workflows/build-one.yml
    with:
      model: mi-r3gv2
